
---

  - name: Copying Sensu configuration files
    template:
      src: "{{ item }}"
      dest: /etc/sensu/conf.d/{{ item | basename | regex_replace('\.j2','') }}
      owner: sensu
      group: sensu
      mode: 0640
    with_fileglob:
      - ./templates/*.j2
    notify: Restart Sensu client

  - name: Checking if this host is a Sensu server
    stat:
      path: /etc/sensu/uchiwa.json
    register: result

  - name: Removing rabbitmq config file if this is a Sensu server
    file:
      path: /etc/sensu/conf.d/rabbitmq.json
      state: absent
    when: result.stat.exists == True

  - name: Starting the Sensu client
    systemd:
      name: sensu-client
      state: started
      enabled: yes

