
---

  - name: Copying Sensu configuration file
    template:
      src: ./templates/client.json.j2
      dest: /etc/sensu/conf.d/client.json
      owner: sensu
      group: sensu
      mode: 0640
    notify: Restarting the Sensu client

  - name: Checking if host is Sensu server
    shell: systemctl status sensu-server
    failed_when: ( result.rc not in [ 0, 3 ] )
    ignore_errors: yes
    register: result

  - name: Copying RabbitMQ configuration file
    template:
      src: ./templates/rabbitmq.json.j2
      dest: /etc/sensu/conf.d/rabbitmq.json
      owner: sensu
      group: sensu
      mode: 0640
    when: '"active (running)" not in result.stdout'

  - name: Starting the Sensu client
    systemd:
      name: sensu-client
      state: started
      enabled: yes

