
---

  - name: Copying sensu config files
    template:
      src: "{{ item }}"
      dest: /etc/sensu/conf.d/{{ item | basename | regex_replace('\.j2','') }}
      owner: sensu
      group: sensu
      mode: 0640
    with_fileglob:
      - ./templates/*.j2
    notify: Restart Sensu client

  - name: Starting sensu client
    systemd:
      name: sensu-client
      state: started
      enabled: yes

