
---

  - name: Installing required packages on RedHat
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - nss
      - curl
      - sysstat

  - name: Installing the Sensu RPM file on RedHat
    yum:
      name: /var/tmp/{{ rpm_sensu }}
      disable_gpg_check: yes
      state: present

